# Generated by Django 2.2.7 on 2019-11-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_list', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('period', models.IntegerField(blank=True, default=24)),
                ('arrival_time', models.IntegerField(blank=True, default=0)),
                ('deadline', models.IntegerField(blank=True, default=24)),
                ('type_work', models.CharField(blank=True, default='work', max_length=100)),
                ('optional', models.BooleanField(default=False)),
                ('start_time_flag', models.BooleanField(default=False)),
                ('start_timing', models.TimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_list', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_efficiency', models.IntegerField()),
                ('weekly_efficiency', models.IntegerField()),
                ('total_efficiency', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('total_weeks', models.IntegerField()),
                ('tasks_attempted', models.IntegerField()),
                ('tasks_completed', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Efficiency',
            },
        ),
    ]
