# Generated by Django 2.2 on 2019-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('period', models.IntegerField()),
                ('arrival_time', models.IntegerField()),
                ('deadline', models.IntegerField()),
                ('type_work', models.CharField(max_length=100)),
                ('start_time_flag', models.BooleanField()),
                ('start_timing', models.TimeField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
    ]
