# Generated by Django 2.2.7 on 2019-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='slot_list',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
