# Generated by Django 2.2 on 2019-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='arrival_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='deadline',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='process',
            name='period',
            field=models.IntegerField(default=24),
        ),
    ]
