# Generated by Django 2.2.7 on 2019-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0002_auto_20191122_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='slot_list',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
