# Generated by Django 2.2 on 2019-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0002_auto_20191113_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='type_work',
            field=models.CharField(default='work', max_length=100),
        ),
    ]
