# Generated by Django 2.2 on 2019-11-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0003_auto_20191113_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='start_timing',
            field=models.TimeField(null=True),
        ),
    ]
