# Generated by Django 2.2.7 on 2019-12-09 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler_project', '0003_auto_20191122_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_list', models.CharField(blank=True, max_length=1000)),
                ('algo', models.CharField(blank=True, max_length=100)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('week', models.IntegerField(blank=True)),
                ('day', models.IntegerField(blank=True)),
                ('efficiency_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_project.Efficiency')),
                ('parameter_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_project.Parameters')),
                ('slot_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_project.Slots')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
