# Generated by Django 2.2.7 on 2019-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
