# Generated by Django 2.2 on 2019-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0004_auto_20191113_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='start_timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
