# Generated by Django 2.2 on 2019-11-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0005_auto_20191113_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='optional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
