# Generated by Django 2.2.7 on 2019-12-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0005_process_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Schedule'},
        ),
    ]
