# Generated by Django 2.2 on 2019-11-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0006_process_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='start_timing',
            field=models.TimeField(null=True),
        ),
    ]
