# Generated by Django 2.2.7 on 2019-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0006_auto_20191210_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
