# Generated by Django 2.2 on 2019-11-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0007_auto_20191113_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_time_flag',
            field=models.BooleanField(default=False),
        ),
    ]
