# Generated by Django 2.2 on 2019-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0008_auto_20191113_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='start_timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
