# Generated by Django 2.2 on 2019-11-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0009_auto_20191113_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='arrival_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='deadline',
            field=models.IntegerField(blank=True, default=24),
        ),
        migrations.AlterField(
            model_name='process',
            name='period',
            field=models.IntegerField(blank=True, default=24),
        ),
        migrations.AlterField(
            model_name='process',
            name='type_work',
            field=models.CharField(blank=True, default='work', max_length=100),
        ),
    ]
