# Generated by Django 2.2 on 2019-11-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_project', '0014_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiency',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='tasks_attempted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='tasks_completed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='total_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='total_weeks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
